### PR TITLE
feat: prompt for name before performing refactors

### LINKED ISSUE #40: Add prompt to name when extracting widget, local variable or method
Another idea inspired by `coc-flutter`, is to intercept code actions such that when a user selects ~`wrap with widget`~ `extract widget` or `extract method` we can show the user a prompt to collect the name to use and send that with the code action request.

I'm not sure how easy the idea of intercepting lsp actions is but this will be similar to how #38 is implemented in the end. There is also some prior art in `coc-flutter` but it won't really work exactly the same given the different underlying mechanics

### PR DESCRIPTION
**Pull request by nghialm269**
Prompt user for name when extracting method, widget and local variable.

The PR works fine now, but waiting for https://github.com/neovim/neovim/pull/16101 for better implementation, and maybe wait for https://github.com/neovim/neovim/pull/15959 so that we can customize the prompt.

Closes #40

### CODE REVIEW

**Comment by nghialm269** [comment]
@akinsho: I don't know where to put the client-side commands, so I'm creating a new file in lsp folder for now, please let me know if you want to change it.

**Comment by akinsho** [comment]
@nghialm269 a new file for commands looks good to me 👍🏿 , seems like the other PR you were waiting for is also merged. Is this ready to merge then. Eventually I'll likely replace the UI for the rename prompt but think it's fine for a first iteration

**Comment by nghialm269** [comment]
@akinsho yes, it's ready to merge now.

I will open a follow-up PR when neovim/neovim#15959 is merged, to change `vim.fn.input` to `vim.ui.input`.

**Comment by akinsho** [comment]
Thanks for your work on this @nghialm269 🎉

**Pull request merged**
