### PR TITLE
feat: resolve package urls when using `gf` or `gF`

### PR DESCRIPTION
**Pull request by sidlatau**

### CODE REVIEW

**Comment by Dieterbe** [comment]
here's what happens when i run 'gf' on lib/backend/muscles.dart: (with nvim launched as `nvim code/ptc` and the lib directory exists directly inside of code/ptc)
error

**Comment by Dieterbe** [comment]
```
flutter --version
Flutter 3.22.3 • channel stable • ssh://git@github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 months ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

`cat code/ptc/.dart_tool/package_config.json` -> https://gist.github.com/Dieterbe/8fa29d233b119bbf07d6926662338527

**Comment by sidlatau** [comment]
@Dieterbe could you test PR again? I fixed a couple of possible issues.

**Comment by Dieterbe** [comment]
this is while pressing 'gf' on a file with path lib/... which shouldn't require any path adjustment (because lib is inside code/ptc and i ran `nvim code/ptc`) image

**Comment by sidlatau** [comment]
@Dieterbe it is hard to understand what is going on from the screenshot. For me both uris with `package:` or without it work as expected. Could you paste the output of `:messages` after trying to use `gf`? Does command work for other links? Maybe you are using `auto-session` plugin? I had some caching problems with it, that caused `gf` issues.

**Comment by Dieterbe** [comment]
I use github.com/LazyVim/starter without any customizations, other than this file:
```
cat lua/plugins/core.lua
return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "tokyonight",
    },
  },
  {
    "akinsho/flutter-tools.nvim",
    lazy = false,
    branch = "resolve-url",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "stevearc/dressing.nvim", -- optional for vim.ui.select
    },
    config = true,
  },
}
```

```
~/.c/nvim ❯❯❯ grep -Ri auto-session
~/.c/nvim ❯❯❯   
```


so, i reproduced the same situation as in my previous comment, and :messages says this:
```
"~/code/ptc/lib/backend/muscles.dart" 246L, 5877B
1 change; before #1  58 seconds ago
"~/code/ptc/lib/backend/muscles.dart" 246L, 5877B
"~/code/ptc/lib/backend/muscles.dart" 246L, 5875B
"~/code/ptc/lib/main.dart" 71L, 2437B
"~/code/ptc/lib/main.dart" 72L, 2480B
Type  :qa  and press <Enter> to exit Nvim
...azy/flutter-tools.nvim/lua/flutter-tools/resolve_url.lua:92: Cannot find package_config.json file
stack traceback:
	[C]: in function 'error'
	...azy/flutter-tools.nvim/lua/flutter-tools/resolve_url.lua:92: in function <...azy/flutter-tools.nvim/lua/flutter-tools/resolve_url.lua:84>
E15: Invalid expression: "v:lua.require('flutter-tools.resolve_url').resolve_url(v:fname)"
E447: Can't find file "lib/ui/muscles_screen.dart" in path
```

**Comment by sidlatau** [comment]
@Dieterbe did you tested with the latest changes? https://github.com/nvim-flutter/flutter-tools.nvim/pull/392/commits/77dd736b040c695f7774d2da0a336d901c60614b should actually use buffer path, previously it tried to find `package_config.json` in CWD. So even if you opened vim with a path argument, it should construct references correctly.

**Comment by sidlatau** [comment]
Yes, it works for me. So I think I will merge this PR, it works in most cases, we may solve edge cases on separate PRs.

**Pull request merged**
